<?php
use App\Database;

$message = json_decode($message, true);

$usersId = "'". implode("','", array_keys($message)) . "'";
$users = Database::getRequest(
    "SELECT `username`, `id`
    FROM `users`
    WHERE `id`
    IN ($usersId)",
    [],
    'fetchAll'
);
// $usersId has generated by db, is an number, no risk of sql injection

foreach ($users as $value) {
    $message[$value['username']] = $message[$value['id']];
    unset($message[$value['id']]);
}

arsort($message);

?>
<div>
    <table>
        <thead>
            <tr>
                <td>Nom d'utilisateur</td>
                <td>Score</td>
            </tr>
        </thead>
        <tbody>
            <?php
                foreach ($message as $key => $value):
                    ?>
                        <tr>
                            <td><?= $key ?></td>
                            <td><?= $value ?></td>
                        </tr>
                    <?php
                endforeach;
            ?>
        </tbody>
    </table>
    <a href="/challenges">Retour</a>
</div>